### ISSUE TITLE
App.js fetch products 

### ISSUE THREAD

**Issue by mz106** [mz106/gh-project-example-lesson-3#3]
From branch feature/app;

In App.js;
Add import useState/useEffect
Add useState products/setProducts

Add useEffect 
Fetch products from https://fakestoreapi.com/products?limit=6
Set products to api data

**Comment by horsellcommon** [comment]
@mz106 Issue cleared with pull request #24

**Comment by mz106** [comment]
Thanks @horsellcommon closing issue
